// <auto-generated />
using LookupFunction.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LookupFunction.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241014134213_m1")]
    partial class m1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("LookupFunction.Models.Organisation", b =>
                {
                    b.Property<string>("OrganisationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("LookupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("OrganisationId");

                    b.ToTable("Organisations");

                    b.HasData(
                        new
                        {
                            OrganisationId = "13803ced-2960-4a4e-851c-94b5cfe80195",
                            Country = "United Kingdom",
                            LookupId = "8-10237731",
                            Name = "Rotary Club of Barnstaple"
                        },
                        new
                        {
                            OrganisationId = "69132e16-7203-48e5-a13a-54ac2bbc7b19",
                            Country = "United Kingdom",
                            LookupId = "8-10237743",
                            Name = "Rotary Club of Hitchin Priory"
                        },
                        new
                        {
                            OrganisationId = "65618224-185f-481e-af10-3900650dce9a",
                            Country = "United Kingdom",
                            LookupId = "8-10237750",
                            Name = "Rotary Club of Market Bosworth"
                        },
                        new
                        {
                            OrganisationId = "c17275cd-6b29-41ff-9768-d4a4fdbc997c",
                            Country = "United Kingdom",
                            LookupId = "8-10237759",
                            Name = "Rotary Club of Dover"
                        },
                        new
                        {
                            OrganisationId = "e0832ca6-867f-4818-ad7a-6de13187afec",
                            Country = "United Kingdom",
                            LookupId = "8-10237834",
                            Name = "Inner Wheel Club of District 17 East Zone"
                        },
                        new
                        {
                            OrganisationId = "872b474e-f148-4965-8e29-3e9463725a9f",
                            Country = "United Kingdom",
                            LookupId = "8-10237872",
                            Name = "Inner Wheel Club of Hayle"
                        },
                        new
                        {
                            OrganisationId = "8a8b1c7a-4708-4cdf-b99d-f949afc1c269",
                            Country = "United Kingdom",
                            LookupId = "8-10237914",
                            Name = "Rotary Club of Mk Watling"
                        },
                        new
                        {
                            OrganisationId = "5c204f1a-40d6-47c9-9add-e0f391b794b3",
                            Country = "United Kingdom",
                            LookupId = "8-10238050",
                            Name = "Inner Wheel Club of Ross on Wye"
                        },
                        new
                        {
                            OrganisationId = "30b7c310-1c4f-4d06-aaf2-864771aeefb1",
                            Country = "United Kingdom",
                            LookupId = "8-10238079",
                            Name = "Inner Wheel Club of Leominster"
                        },
                        new
                        {
                            OrganisationId = "af45bf68-ad67-4619-8849-2d602630fafb",
                            Country = "United Kingdom",
                            LookupId = "8-10238092",
                            Name = "Rotary Club of Bridgwater"
                        },
                        new
                        {
                            OrganisationId = "f4d1f57d-7fc3-41e9-b554-fbf0929a130a",
                            Country = "United Kingdom",
                            LookupId = "8-10238097",
                            Name = "Rotary Club of Bury"
                        },
                        new
                        {
                            OrganisationId = "74a09f63-b6ed-47e9-89f0-7d38066543ed",
                            Country = "United Kingdom",
                            LookupId = "8-10238099",
                            Name = "Rotary Club of Haddington"
                        },
                        new
                        {
                            OrganisationId = "76fdd04c-484f-4a71-8f8c-420686afe6a5",
                            Country = "United Kingdom",
                            LookupId = "8-10238100",
                            Name = "Rotary Club of Helston"
                        },
                        new
                        {
                            OrganisationId = "1989d138-791f-460d-8573-c4118f9d54bf",
                            Country = "United Kingdom",
                            LookupId = "8-10238123",
                            Name = "Interact Club of Interact Clubs of Bexley & Hamburg-Harburg"
                        },
                        new
                        {
                            OrganisationId = "0abd7a2f-918e-4ded-a651-7b763c468c80",
                            Country = "United Kingdom",
                            LookupId = "8-10238178",
                            Name = "Inner Wheel Club of Worthing"
                        },
                        new
                        {
                            OrganisationId = "f50e6933-ac7f-4e31-b23b-e247065042aa",
                            Country = "United Kingdom",
                            LookupId = "8-10238193",
                            Name = "Rotary Club of Cardigan"
                        },
                        new
                        {
                            OrganisationId = "6558e8f1-a607-4e5d-be7b-c73e243fd0b9",
                            Country = "United Kingdom",
                            LookupId = "8-10238205",
                            Name = "Rotary Club Of Kings Lynn Priory"
                        },
                        new
                        {
                            OrganisationId = "fec51c57-d00b-4c03-84d8-a631a91f045f",
                            Country = "United Kingdom",
                            LookupId = "8-10238214",
                            Name = "Rotaract Club of Cambridge"
                        },
                        new
                        {
                            OrganisationId = "172151af-35d7-41d7-87e1-03aed1f922c9",
                            Country = "United Kingdom",
                            LookupId = "8-10238215",
                            Name = "Inner Wheel Club of Axminster"
                        },
                        new
                        {
                            OrganisationId = "ae3e8b16-6bce-47ee-a8a0-60e6341bc181",
                            Country = "United Kingdom",
                            LookupId = "8-10238255",
                            Name = "Inner Wheel District 6"
                        },
                        new
                        {
                            OrganisationId = "fc40b064-6a20-496d-8a4b-379b12df34c6",
                            Country = "United Kingdom",
                            LookupId = "8-10238282",
                            Name = "Rotary Club of Shepperton and Sunbury"
                        },
                        new
                        {
                            OrganisationId = "8752e313-d09d-4bba-a1c1-53e842e77ec7",
                            Country = "United Kingdom",
                            LookupId = "8-10238298",
                            Name = "Inner Wheel Club of Londonderry"
                        },
                        new
                        {
                            OrganisationId = "98dc4146-9111-4c55-b14c-a3d6762d7136",
                            Country = "United Kingdom",
                            LookupId = "8-10238315",
                            Name = "Inner Wheel Club of Darent Valley"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
